name: Build libmpv-android

on:
  # 手动触发事件
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      # - name: Bundle (full)
      #   working-directory: ./buildscripts
      #   run: |
      #     sudo chmod +x bundle_full.sh
      #     ./bundle_full.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./buildscripts/*.jar
      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            buildscripts/*.jar
