name: 更新libmpv和media-kit-android-helper

on:
  schedule:
    - cron: '0 19 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 设置Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: 设置标签日期
      run: echo "tag_date=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: 检查libmpv-android更新
      id: check_libmpv
      run: |
        latest_version=$(curl -s https://api.github.com/repos/jarnedemeulemeester/libmpv-android/releases/latest | jq -r .tag_name)
        echo "Latest version: $latest_version"
        echo "latest_version=$latest_version" >> $GITHUB_ENV
        if [ ! -f "last_version.txt" ] || [ "$latest_version" != "$(cat last_version.txt)" ]; then
          echo "update_available=true" >> $GITHUB_ENV
        else
          echo "update_available=false" >> $GITHUB_ENV
        fi

    - name: 下载最新的libmpv发布版
      if: env.update_available == 'true'
      run: |
        curl -L -o libmpv-release.aar https://github.com/jarnedemeulemeester/libmpv-android/releases/latest/download/libmpv-release.aar
        echo "${{ env.latest_version }}" > last_version.txt

    - name: 克隆media-kit-android-helper
      if: env.update_available == 'true'
      run: git clone --depth 1 --branch main https://github.com/media-kit/media-kit-android-helper.git

    - name: 构建media-kit-android-helper
      if: env.update_available == 'true'
      run: |
        cd media-kit-android-helper
        chmod +x gradlew
        ./gradlew assembleRelease
        unzip -q -o app/build/outputs/apk/release/app-release.apk -d app/build/outputs/apk/release

    - name: 提取并合并库文件
      if: env.update_available == 'true'
      run: |
        mkdir -p temp_lib
        unzip -q libmpv-release.aar -d temp_lib
        mkdir -p lib/{arm64-v8a,armeabi-v7a,x86,x86_64}
        mv temp_lib/jni/arm64-v8a/* lib/arm64-v8a/
        mv temp_lib/jni/armeabi-v7a/* lib/armeabi-v7a/
        mv temp_lib/jni/x86/* lib/x86/
        mv temp_lib/jni/x86_64/* lib/x86_64/
        rm -rf temp_lib
        cp media-kit-android-helper/app/build/outputs/apk/release/lib/arm64-v8a/libmediakitandroidhelper.so lib/arm64-v8a/
        cp media-kit-android-helper/app/build/outputs/apk/release/lib/armeabi-v7a/libmediakitandroidhelper.so lib/armeabi-v7a/
        cp media-kit-android-helper/app/build/outputs/apk/release/lib/x86/libmediakitandroidhelper.so lib/x86/
        cp media-kit-android-helper/app/build/outputs/apk/release/lib/x86_64/libmediakitandroidhelper.so lib/x86_64/

    - name: 创建JAR文件并计算MD5
      if: env.update_available == 'true'
      run: |
        zip -r "default-arm64-v8a.jar" "lib/arm64-v8a"
        zip -r "default-armeabi-v7a.jar" "lib/armeabi-v7a"
        zip -r "default-x86.jar" "lib/x86"
        zip -r "default-x86_64.jar" "lib/x86_64"
        md5sum *.jar > default_md5.txt

    - name: 创建Release
      if: env.update_available == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag_date }}
        release_name: Release ${{ env.tag_date }}
        draft: false
        prerelease: false

    - name: 上传到Release
      if: env.update_available == 'true'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          *.jar
          default_md5.txt
        tag_name: ${{ env.tag_date }}

    - name: 提交版本更新
      if: env.update_available == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add last_version.txt
        git commit -m "Update libmpv-android to version ${{ env.latest_version }}"
        git push