name: Build libmpv-android

on:
  # 手动触发事件
  workflow_dispatch:
    # 定时检查
  schedule:
    - cron: '0 14 * * 1'
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Show Space
        run: |
          df -hT $PWD
      - name: Free Disk Space (Ubuntu)
        uses: insightsengineering/disk-space-reclaimer@v1
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tools-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          docker-images: true
      - name: Show Space
        run: |
          df -hT $PWD
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.x"
          check-latest: true
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      - name: Bundle (full)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_full.sh
          ./bundle_full.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./buildscripts/*.jar
      - id: set_tag_date
        run: echo "tag_date=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.tag_date }}
          files: |
            buildscripts/*.jar
